name: Build and Release APK

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to release'
        required: true
        default: 'v3.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon --stacktrace
        
    - name: List APK files (debug)
      run: |
        echo "Checking APK output directory..."
        ls -la app/build/outputs/apk/release/ || echo "Release directory not found"
        find . -name "*.apk" -type f || echo "No APK files found"
        
    - name: Rename APK
      run: |
        if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
          mv app/build/outputs/apk/release/app-release-unsigned.apk weather-widget-${{ github.event.release.tag_name || inputs.version }}.apk
        elif [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
          mv app/build/outputs/apk/release/app-release.apk weather-widget-${{ github.event.release.tag_name || inputs.version }}.apk
        else
          echo "No APK file found to rename"
          exit 1
        fi
        
    - name: Upload APK to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./weather-widget-${{ github.event.release.tag_name }}.apk
        asset_name: weather-widget-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload APK as Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: weather-widget-apk
        path: ./weather-widget-${{ inputs.version }}.apk 