name: Build and Release APK

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to release'
        required: true
        default: 'v3.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Sign APK
      run: |
        # For now, we'll use debug signing. In production, you'd want to use a release keystore
        echo "Using debug keystore for signing..."
        
    - name: Rename APK
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned.apk weather-widget-v${{ github.event.release.tag_name || inputs.version }}.apk || \
        mv app/build/outputs/apk/release/app-release.apk weather-widget-v${{ github.event.release.tag_name || inputs.version }}.apk
        
    - name: Upload APK to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./weather-widget-v${{ github.event.release.tag_name }}.apk
        asset_name: weather-widget-v${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload APK as Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: weather-widget-apk
        path: ./weather-widget-v${{ inputs.version }}.apk 