name: Simple APK Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to release'
        required: true
        default: 'v3.0'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build APK
      run: ./gradlew assembleRelease --no-daemon --warning-mode all
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: weather-widget-${{ inputs.version }}
        path: app/build/outputs/apk/release/app-release-unsigned.apk 